version: '2'
services:
  api:
    build: Docker/PHP7
    restart: never
    volumes:
      - ./web:/var/www/html
      - ./Docker/PHP7/opcache.ini:/etc/php/7.0/etc/conf.d/opcache.ini
      #- ./Docker/PHP7/php.ini:/etc/php/7.0/apache2/php.ini
      - ./Docker/PHP7/php-cli.ini:/etc/php/7.0/cli/php.ini
    ports:
      - "80:80"
    links:
      - mysql
      - memcache

  mysql:
    image: mysql:5.7
    restart: never
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hostapi
      - MYSQL_DATABASE=cursos
    volumes:
      - ./Docker/Mysql/data:/var/lib/mysql

  memcache:
    build: Docker/Memcache
    ports:
      - "11211:11211"
