version: '2'
services:
  php7fpm:
    build: Docker/NginxPHP7/PHP7-FPM
    restart: never
    volumes:
      - ./web:/var/www/html
      # - ./Logs/PHP7:/tmp/logs
      # - ./Docker/PHP7/php-prod.ini:/etc/php/7.0/cli/php.ini
      # - ./Docker/PHP7/opcache.ini:/etc/php/7.0/cli/conf.d/10-opcache.ini
      #- ./Docker/PHP7/php-cli.ini:/etc/php/7.0/cli/php.ini
    ports:
      - "9000"
    links:
      - mysql
      - memcache

  nginxphp7:
    build: Docker/NginxPHP7/Nginx
    restart: never
    volumes:
      - ./Docker/NginxPHP7/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/NginxPHP7/Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php7fpm

  mysql:
    image: mysql:5.7
    restart: never
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hostapi
      - MYSQL_DATABASE=cursos
    volumes:
      - ./Docker/Mysql/data:/var/lib/mysql

  memcache:
    build: Docker/Memcache
    ports:
      - "11211:11211"
